const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 220,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 11,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 350,
      countInStock: 15,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 13,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 145,
      countInStock: 25,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pant",
      image: "/images/p5.jpg",
      price: 70,
      countInStock: 30,
      brand: "Puma",
      rating: 3.5,
      numReviews: 11,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pant",
      image: "/images/p6.jpg",
      price: 410,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Jeans Shirt",
      category: "Pant",
      image: "/images/p7.jpg",
      price: 610,
      countInStock: 3,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Denim Shirt",
      category: "Shirt",
      image: "/images/p8.jpg",
      price: 850,
      countInStock: 8,
      brand: "Denim",
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "Denim Slim Shirt",
      category: "Shirt",
      image: "/images/p9.png",
      price: 210,
      countInStock: 0,
      brand: "Denim",
      rating: 4.9,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
