const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 350,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 13,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 145,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pant",
      image: "/images/p5.jpg",
      price: 70,
      brand: "Puma",
      rating: 4.5,
      numReviews: 11,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pant",
      image: "/images/p6.jpg",
      price: 410,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
